num = [2, 5, 9, 1]
print(num)
num[2] = 3
print(num)
num.append(7)
print(num)
num.sort()
print(num)
num.sort(reverse=True)
print(num)
num.pop(1)
print(num)
num.insert(2, 4)
print(num)
num.remove(4)
print(f'Essa lista tem {len(num)} elementos.')
num.clear()
print(num)
